# Generated by Django 5.0.1 on 2024-01-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='subjects_electronic_network',
            field=models.CharField(choices=[('0', 'Factory'), ('1', 'Retail'), ('2', 'Individual entrepreneur')], max_length=50, verbose_name='Субъект торговой сети'),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateField(verbose_name='Дата реализации'),
        ),
    ]
